### ISSUE TITLE
Inspector/Asset Browser: Not selecting the file when right-clicking Open in Explorer

### ISSUE THREAD

**Issue by kristiker** [sboxgame/issues#2966]
### Describe the bug

When I try to `Open Asset in Explorer` in Inspector or Asset Browser, it opens the folder but doesn't select the file!

If there are many files on the folder this makes it hard to know which one was right clicked!

### To Reproduce
- Find an asset in asset browser
- Click `Open Asset Location in File Explorer`
- Folder opens, but asset is not selected!

### Expected behavior

Highlight the asset

### Additional context

Windows explorer has the option `/select` that can be used to select the file.

**Comment by robotboy655** [comment]
Should be working like you want it to when the game next updates.

**Comment by kristiker** [comment]
<img src="https://user-images.githubusercontent.com/26466974/226725273-b636fc0d-bf7b-4f3d-9dc2-aad7f5fd8c1a.png" width=50%>

Asset Browser yes, Inspector still not.
