### ISSUE TITLE
Can't compile map with new Vis3

### ISSUE THREAD

**Issue by MrBrax** [sboxgame/issues#3050]
### Describe the bug

With my (quite large and detailed) open world map, new vis seems to just freeze after half an hour or so (or just a couple minutes now in my last test). I kept it going overnight but it didn't continue, using 100% cpu. Old vis took maybe half an hour to an hour, can't really remember but it worked.

Cordoning does not help either.

However, an instance from the map works just fine.

### To Reproduce

1. Build map with vis enabled

### Expected behavior

To compile

### Media/Files

<img width="349" alt="1679416828946" src="https://user-images.githubusercontent.com/1517911/226857614-7c634e2b-8aea-4aef-ad2b-06c7da5cdb57.png">

<img width="150" alt="1679468559472" src="https://user-images.githubusercontent.com/1517911/226857630-44fe11d2-4f25-4b69-9cc1-36ed19d8e9e8.png">

Logs show nothing related other than a freeze.

```
2023/03/22 10:19:23.2853	engine/Engine	Bailing out of OnBlockForQuery after 0.250 seconds	
2023/03/22 10:19:23.5490	engine/Engine	Bailing out of OnBlockForQuery after 0.250 seconds	
2023/03/22 10:20:06.6009	engine/Engine	Bailing out of OnBlockForQuery after 0.250 seconds	
2023/03/22 10:21:57.7423	engine/HangWatchdog	Hang detected.	
2023/03/22 10:22:05.7342	engine/HangWatchdog	Hang detected.	
```

**Comment by ogniK5377** [comment]
Can you please attach the map you're trying to compile?

**Comment by MrBrax** [comment]
[newcity.zip](https://github.com/sboxgame/issues/files/11039179/newcity.zip)

Here it is, hope the dependencies load.

**Comment by aylaylay** [comment]
There are many missing dependencies, do you have the whole thing on a repo instead?

**Comment by MrBrax** [comment]
The entire private map repo is close to 6.5 gigs, but I could maybe add you as a collaborator, if that's how it works on github?

**Comment by aylaylay** [comment]
Even with the errors I think I can get it to spit out the same errors as you so that should be enough to see what's going wrong.

**Comment by aylaylay** [comment]
I have disabled the log that is being spammed which was causing the editor to hang, it should compile now but I'm going to find out why this log is happening and if it's harmless or not.

**Comment by aylaylay** [comment]
In the example you gave me, it took about 5 mins to compile vis.

**Comment by MrBrax** [comment]
Nice, seems to get further now, took 25 minutes for me for the full map. Will test performance when vrad is done.

**Comment by MrBrax** [comment]
Performance might have doubled for me in certain spots, but i never did an actual test in beforehand. Good update.

**Comment by aylaylay** [comment]
Just an update on this @MrBrax I found the actual problem and it should be fixed now, if you recompile again it should have no issue and the vis should be correct (and probably better)

**Comment by MrBrax** [comment]
Nice, launching a full 4096 compile over the day. I did notice things outside drawing with wireframe on when i was inside previously working structures.

**Comment by MrBrax** [comment]
![20230324155323_1](https://user-images.githubusercontent.com/1517911/227559796-f99d6a1e-d8e2-4203-a043-2e4966d6a6c4.jpg)

Still getting a lot of visible geometry through walls, is the merging of edges crucial for performance?
