### ISSUE TITLE
Cubemaps fail to compile

### ISSUE THREAD

**Issue by WujekFoliarz** [sboxgame/issues#3827]
### Describe the bug

I am unable to compile cubemaps, no matter what I do it just doesn't work. I asked a guy with the exact same problem and we both have a 6000 series amd gpu, might be related to them or amd cards in general.

```
 12:58:25   > buildcubemaps
 12:58:25   engine/Engine Visibility disabled.
 12:58:25   engine/BuildCubemaps Writing cubemaps to c:\users\user\documents\s&box projects\mapping_stuff\maps\plotmap.vpk
 12:58:25   engine/BuildCubemaps Waiting for rendering to complete...
 12:58:25   engine/BuildCubemaps Building 3 cubemaps, rendering: 1024x1024, storage: 256x256
 12:58:25   engine/BuildCubemaps d:\gry\steam games\steamapps\common\sbox\core\_buildcubemaps\env_cubemap_1639507407.exr
 12:58:25   engine/BuildCubemaps d:\gry\steam games\steamapps\common\sbox\core\_buildcubemaps\env_cubemap_1639507406.exr
 12:58:25   engine/BuildCubemaps d:\gry\steam games\steamapps\common\sbox\core\_buildcubemaps\env_cubemap_global.exr
 12:58:25   engine/BuildCubemaps Finished (0.4 seconds)
 12:58:25   engine/BuildCubemaps Running command: resourcecompiler  -noassert -i env_cubemap_array.vtex
 12:58:26   engine/BuildCubemaps Failed command: resourcecompiler  -noassert -i env_cubemap_array.vtex
 12:58:26   engine/BuildCubemaps Moving D:\Gry\Steam Games\steamapps\common\sbox\core\_buildcubemaps.vpk to D:\Gry\Steam Games\steamapps\common\sbox\.source2\_buildcubemaps.vpk
 12:58:26   engine/BuildCubemaps Disconnecting for the purpose of editing c:\users\user\documents\s&box projects\mapping_stuff\maps\plotmap.vpk
 12:58:26   engine/Engine Unable to remove D:\Gry\Steam Games\steamapps\common\sbox\core\_buildcubemaps!
 12:58:26   engine/Engine Visibility enabled.
 12:58:26   engine/Client CL:  disconnect
12:58:26   engine/Client CL:  Disconnecting from server: NETWORK_DISCONNECT_DISCONNECT_BY_USER
 12:58:26   engine/Engine Unable to remove D:\Gry\Steam Games\steamapps\common\sbox\.source2\_buildcubemaps!
 12:58:26   engine/BuildCubemaps Unzipping c:\users\user\documents\s&box projects\mapping_stuff\maps\plotmap.vpk (24 files)
 12:58:26   engine/BuildCubemaps Unzipping D:\Gry\Steam Games\steamapps\common\sbox\.source2\_buildcubemaps.vpk (4 files)
 12:58:26   engine/BuildCubemaps Zipping c:\users\user\documents\s&box projects\mapping_stuff\maps\plotmap.vpk (28 files)
 12:58:26   engine/BuildCubemaps Re-loading map maps/plotmap.vpk
 12:58:26   engine/Console Loading map "maps/plotmap"
 12:58:26   engine/RenderSystem Deleting texture with outstanding streaming request (materials/bricks/plainbrick/bricks066_4k_normaldx_jpg_b7d6eff3.generated.vtex)
 12:58:26   engine/NetSteamConn Steam Net connection #899867235 pipe closed by peer, reason 1001: NETWORK_DISCONNECT_SHUTDOWN
 12:58:26   engine/Server SV:  maxplayers set to 8
 12:58:26   ServerDll CurrentGamemode: Sandbox
 12:58:27   ServerDll Found 1 GameManagers
 12:58:27   ServerDll 1. SandboxGame (package.facepunch.sandbox, Version=0.0.111.0, Culture=neutral, PublicKeyToken=null)
 12:58:27   engine/ResourceSystem Error loading resource file "maps/plotmap/cubemaps/env_cubemap_array.vtex_c" (Error: ERROR_FILEOPEN: File not found)
 12:58:28   Server "Wujek_Foliarz" has joined the game
 12:58:28   Server Couldn't find spawnpoint for SandboxPlayer 77!
```

### To Reproduce

1. Click build map in hammer
2. Check the "Build cubemaps on load" option
3. Load the map
4. Cubemaps don't show up

### Expected behavior

Cubemaps should compile and show up both in hammer and the game

### Media/Files

![image](https://github.com/sboxgame/issues/assets/72314465/63ec1348-d807-4e71-b496-08277f6684a0)
![image](https://github.com/sboxgame/issues/assets/72314465/4a56e06e-c5ac-42fe-95a8-e935176db342)
![image](https://github.com/sboxgame/issues/assets/72314465/2a94df0d-2406-4b51-b3ba-5e714686f23f)

### Additional context

Windows 11
Ryzen 5 3600
RX 6600 XT 8GB
16 GB RAM

**Comment by Glitchvid** [comment]
Also having this issue.
Worth mentioning this happens with both ingame and VRAD2 cubemaps.

Windows 10 Pro 22H2
i7-6850K
AMD RX 7900 XTX 
Driver version: 23.10.23.02

This is NOT a problem on my build system
Windows 10 Pro 22H2
Ryzen 3950X
AMD R9 290
Driver Version: 21.09.13.02

**Comment by eyedine2** [comment]
still not fixed (I was the other guy mentioned in the OP)

AMD RX 6600
Ryzen 9 3900X
32 GB RAM
Windows 10 Pro 22H2

**Comment by WujekFoliarz** [comment]
I just tried it on my friend's PC and the bug was present.

RX6600XT
Ryzen 5 3600
16GB RAM
Windows 10

**Comment by aylaylay** [comment]
Unless this is a different bug, this should hopefully be fixed now

**Comment by Glitchvid** [comment]
Still broken for me.
`04:06:56   engine/BuildCubemaps Running command: resourcecompiler  -noassert -i env_cubemap_array.vtex`
`04:06:59   engine/BuildCubemaps Failed command: resourcecompiler  -noassert -i env_cubemap_array.vtex`

**Comment by handsomematt** [comment]
I can see your crash, you didn't update the game.

**Comment by Glitchvid** [comment]
I updated Sbox so I could launch the game to test, looks like there was latency between you guys pushing the build and Steam publishing your fixed built at least for my region.
It looks fixed now, thanks.
