### ISSUE TITLE
error.sound doesn't exist, yet it is referenced by Cloud.SoundEvent

### ISSUE THREAD

**Issue by rndtrash** [sboxgame/issues#3839]
### Describe the bug

[Sandbox.Cloud.SoundEvent](https://asset.party/api/Sandbox.Cloud.SoundEvent(string)) uses `error.sound` as a fallback when it can't find a sound with given ident. While `error_00*.vsnd_c` files already exist in the core folder, there is no sound event that references these, thus Sandbox.Cloud.SoundEvent returns null.

### To Reproduce

1. Call Sandbox.Cloud.SoundEvent with any ident (it doesn't work even for valid sound assets???)
2. It will return null

### Expected behavior

I expect `error.sound` to exist, or at least having an option to return null instead of a placeholder.

### Media/Files

My own error.sound that uses the Kenney error sounds: [error.sound.txt](https://github.com/sboxgame/issues/files/12329377/error.sound.txt)

**Comment by bakscratch** [comment]
Should be fixed now.

**Comment by rndtrash** [comment]
Almost fixed, the file is located in a folder sounds/**tools**, but Cloud.SoundEvent references error.sound in sounds/, oops!
```cs
public static Sandbox.SoundEvent SoundEvent([StringLiteralOnly] string ident) => Cloud.GetCloudAsset<Sandbox.SoundEvent>(ident, Cloud.\u003C\u003EO.\u003C3\u003E__Load ?? (Cloud.\u003C\u003EO.\u003C3\u003E__Load = new Func<string, Sandbox.SoundEvent>(GameResource.Load<Sandbox.SoundEvent>)), (Func<Sandbox.SoundEvent>) (() => GameResource.Load<Sandbox.SoundEvent>("sounds/error.sound")));
```
~~also oh my god you forgot to add "sounds/kenney/ui/error_008.vsnd"~~

**Comment by rndtrash** [comment]
I don't need it, it's just weird that this file is unused 😕

Anyway, it works now, thanks!
